[phases.setup]
nixPkgs = ["nodejs-20_x", "npm"]

[phases.install]
cmds = ["cd api && npm ci"]

[phases.build]
cmds = [
  "cd api && npx prisma generate",
  "cd api && npm run build",
]

[start]
cmd = "cd api && npx prisma generate && npx prisma migrate deploy && npm run start:prod"
